name: Build and Run Node App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Start app briefly to check for runtime errors
        env:
          NODE_ENV: production
          ATLASDB_URL: ${{ secrets.ATLASDB_URL }}
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
          CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
          CLOUD_Name: ${{ secrets.CLOUD_Name }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          node app.js &
          sleep 5
          echo "App started successfully. Stopping..."
